---
format: gfm
params:
    city: "Miami"
    max_pop: 100000
    nthreads: 4
    echo: false
    seed: 8812
    ndays: 100
    nsims: 50
---

## Preparing the environment

```{r}
#| label: loading-libraries
#| warning: false
#| message: false
library(measles)
library(data.table)

if (!exists("params")) {
  params <- list(
    city = "Miami",
    max_pop = 100000,
    nthreads = 4,
    echo = FALSE,
    seed = 8812,
    ndays = 100,
    nsims = 50
    )
}

knitr::opts_chunk$set(
  echo = params$echo,
  warning = FALSE,
  message = FALSE
)

```


```{r}
#| label: loading-data
# Population matrix
census_age <- fread("data/census_age.csv")[city == params$city]
population <- fread("data/population.csv")[city == params$city]

# Mixing matrix (age-based, from POLYMOD survey data)
mixing_matrices <- readRDS("data/mixing_matrix.rds")
available_cities <- names(mixing_matrices)

if (!(params$city %in% available_cities)) {
  stop(
    sprintf(
      "Unknown city '%s' in params$city. Available cities in data/mixing_matrix.rds: %s",
      params$city,
      paste(available_cities, collapse = ", ")
    )
  )
}

mixing <- mixing_matrices[[params$city]]

# Retrieving vaccination rate
vacc_rate <- fread(
  "data/mmr.csv",
  comment.char = "#"
  )[city == params$city]$vacc_rate / 100
```

```{r}
#| label: adjusting-population
N <- min(params$max_pop, sum(population$Population))
census_age[, total := ceiling(total/sum(total) * N)]
census_age[, vacc_rate := vacc_rate]

N <- sum(census_age$total)
```

## Baseline scenario

```{r}
#| label: creating-model

# Finding hospitalization rate for
# a 10% hospitalization probability
# P(hosp) = hosp_r / (hosp_r + rec_r)
#   => hosp_r = P(hosp) (hosp_r + rec_r)
#             = P(hosp) * hosp_r + P(hosp) * rec_r
#   => hosp_r = P(hosp) * rec_r / (1 - P(hosp))
h_rate <- 0.1 * (1 / 3) / (1 - 0.1)

measles_model <- ModelMeaslesMixing(
  n                            = N,
  prevalence                   = 1,
  contact_rate                 = 15 / 0.9 / 4,
  transmission_rate            = 0.9,
  vax_efficacy                 = 0.97,
  contact_matrix               = mixing,
  hospitalization_rate         = h_rate,
  hospitalization_period       = 7,
  days_undetected              = 2,
  quarantine_period            = 21,
  quarantine_willingness       = 0.9,
  isolation_willingness        = 0.9,
  isolation_period             = 4,
  prop_vaccinated              = 0.95,
  contact_tracing_success_rate = 0.8,
  contact_tracing_days_prior   = 4,
  rash_period                  = 3
)
```


```{r}
#| label: adding-entities
# Adding the entities to the model
add_entities_from_dataframe(
  model = measles_model,
  entities = census_age,
  col_name = "age_group",
  col_number = "total",
  as_proportion = FALSE
)
```



```{r}
#| label: setting-distribution
# Creating the distribution function
dist_fun <- distribute_tool_to_entities(
  prevalence = census_age$vacc_rate,
  as_proportion = TRUE
)

# Setting the distribution function
measles_model |>
  get_tool(0) |>
  set_distribution_tool(dist_fun)
```


```{r}
#| label: distribute-initial-cases
get_virus(measles_model, 0L) |>
  set_distribution_virus(
    distfun = distribute_virus_randomly(prevalence = 1, as_proportion = FALSE)
  )
```

```{r}
#| label: running-simulations
measles_model |>
  run_multiple(
    ndays = params$ndays,
    nsims = params$nsims,
    seed  = params$seed,
    saver = make_saver("outbreak_size", "hospitalizations"),
    nthreads = params$nthreads
  )
```


```{r}
#| label: extracting-results
# Extracting the results
ans <- measles_model |>
  run_multiple_get_results(
    freader = data.table::fread
  )

# Taking a look at the structure
if (params$echo) {
  str(ans)
}

# Converting into data.table format for convenience
outbreak_size <- ans$outbreak_size |> as.data.table()
hospitalizations <- ans$hospitalizations |> as.data.table()
```


```{r}
#| label: plotting-outbreak-size1
# Aggregating to get the final
with(
  outbreak_size,
  {
    plot(
      x = date,
      y = outbreak_size,
      col = adjustcolor("blue", alpha.f = .2),
      pch = 19,
      ylab = "Cases",
      xlab = "Day",
      main = "Measles outbreak size in Short Creek",
      sub = "Mixing model with age and school data (100 simulations)"
    )
})
```


```{r}
#| label: plotting-outbreak-size2
# Aggregating to get the final
with(
  outbreak_size[date == max(date)],
  {
    hist(
      outbreak_size,
      main = "Measles outbreak size in Short Creek",
      sub = "Mixing model with age and school data (100 simulations)",
      breaks = 20
    )
})
```


## Session info

This document was generated using the `{measles}` R package version `r packageVersion("measles")` and the `{epiworldR}` package version `r packageVersion("epiworldR")` on `r Sys.Date()`. We used R version `r getRversion()`, running on `r Sys.info()[['sysname']]` with `r Sys.info()[['machine']]` architecture.

