#!/usr/bin/env python3
"""
generate_data.py
----------------
Reads the same simulation outputs used by README.qmd and writes
docs/data.js – a JavaScript file that defines the CITIES constant
consumed by docs/index.html.

Sources (relative to the repo root):
  scenarios/<City>_outbreak_size.csv  – per-simulation daily outbreak sizes
  data/mmr.csv                        – MMR vaccination rates by city
  data/population.csv                 – city populations
"""

import csv
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCENARIOS_DIR = os.path.join(REPO_ROOT, "scenarios")
MMR_CSV       = os.path.join(REPO_ROOT, "data", "mmr.csv")
POP_CSV       = os.path.join(REPO_ROOT, "data", "population.csv")
OUT_JS        = os.path.join(REPO_ROOT, "docs", "data.js")

# Geographic coordinates for each host city
COORDS = {
    "Atlanta":       {"lat":  33.7490, "lng":  -84.3880},
    "Boston":        {"lat":  42.3601, "lng":  -71.0589},
    "Dallas":        {"lat":  32.7767, "lng":  -96.7970},
    "Houston":       {"lat":  29.7604, "lng":  -95.3698},
    "Kansas City":   {"lat":  39.0997, "lng":  -94.5786},
    "Los Angeles":   {"lat":  34.0522, "lng": -118.2437},
    "Miami":         {"lat":  25.7617, "lng":  -80.1918},
    "New York City": {"lat":  40.7128, "lng":  -74.0060},
    "Philadelphia":  {"lat":  39.9526, "lng":  -75.1652},
    "San Francisco": {"lat":  37.7749, "lng": -122.4194},
    "Seattle":       {"lat":  47.6062, "lng": -122.3321},
}


def read_csv_skip_comments(path):
    """Return a csv.DictReader that skips lines starting with '#'."""
    with open(path, newline="") as fh:
        rows = [r for r in fh if not r.startswith("#")]
    return list(csv.DictReader(rows))


def read_seed_cases(city):
    """
    Parse scenarios/<City>.md to find the number of seed (initial) cases.
    Looks for the line: "We will use N initial cases in the simulations"
    Falls back to 1 if the file is missing or the pattern is not found.
    """
    import re
    fn = os.path.join(SCENARIOS_DIR, f"{city}.md")
    if not os.path.exists(fn):
        print(f"WARNING: missing {fn}, defaulting seed_cases to 1", file=sys.stderr)
        return 1
    pattern = re.compile(r"We will use (\d+) initial cases in the simulations")
    with open(fn) as fh:
        for line in fh:
            m = pattern.search(line)
            if m:
                return int(m.group(1))
    print(f"WARNING: seed case count not found in {fn}, defaulting to 1", file=sys.stderr)
    return 1


def compute_probs(city, cuts=(10, 20, 50)):
    """
    Read scenarios/<city>_outbreak_size.csv, find the final day's
    outbreak size for each simulation, and return P(size >= cut)
    for each cut-off as well as the number of simulations.
    """
    fn = os.path.join(SCENARIOS_DIR, f"{city}_outbreak_size.csv")
    if not os.path.exists(fn):
        print(f"WARNING: missing {fn}", file=sys.stderr)
        return {f"prob_{c}": None for c in cuts} | {"n_sims": 0}

    # Build {sim_num: (max_date, final_size)}
    final = {}
    with open(fn, newline="") as fh:
        for row in csv.DictReader(fh):
            sim  = int(row["sim_num"])
            date = int(row["date"])
            size = int(row["outbreak_size"])
            if sim not in final or date > final[sim][0]:
                final[sim] = (date, size)

    # Keep only rows at the true maximum date
    max_date = max(v[0] for v in final.values())
    sizes    = [v[1] for v in final.values() if v[0] == max_date]
    n        = len(sizes)

    result = {"n_sims": n}
    for cut in cuts:
        result[f"prob_{cut}"] = round(sum(s >= cut for s in sizes) / n, 4) if n else None
    return result


def main():
    # --- vaccination rates ---
    mmr = {r["city"]: float(r["vacc_rate"]) for r in read_csv_skip_comments(MMR_CSV)}

    # --- populations ---
    pop = {r["city"]: int(r["Population"]) for r in read_csv_skip_comments(POP_CSV)}

    # --- assemble city records ---
    cities = []
    for city, coords in COORDS.items():
        probs = compute_probs(city)
        seed  = read_seed_cases(city)
        cities.append({
            "name":       city,
            "lat":        coords["lat"],
            "lng":        coords["lng"],
            "prob_10":    probs.get("prob_10"),
            "prob_20":    probs.get("prob_20"),
            "prob_50":    probs.get("prob_50"),
            "vacc":       mmr.get(city),
            "pop":        pop.get(city),
            "n_sims":     probs.get("n_sims", 0),
            "seed_cases": seed,
        })
        print(f"  {city}: prob_10={probs.get('prob_10')}, vacc={mmr.get(city)}%, n_sims={probs.get('n_sims')}, seed_cases={seed}")

    # --- write docs/data.js ---
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w") as fh:
        fh.write("// Auto-generated by docs/generate_data.py – do not edit by hand.\n")
        fh.write("// Source: scenarios/*_outbreak_size.csv, scenarios/*.md, data/mmr.csv, data/population.csv\n")
        fh.write("const CITIES = ")
        json.dump(cities, fh, indent=2)
        fh.write(";\n")

    print(f"\nWrote {OUT_JS}")


if __name__ == "__main__":
    main()
